# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Potluck' do
  use_frameworks!

  # Pods for Potluck
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  pod 'ScalingCarousel'
  pod 'SVProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  
  target 'PotluckTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Facebook'
    pod 'FirebaseUI/Phone'
    pod 'Firebase/Database'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Firestore'
    pod 'ScalingCarousel'
    pod 'SVProgressHUD'
    pod 'Kingfisher', '~> 5.0'
  end

end
