# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Potluck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Potluck
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  pod 'ScalingCarousel'
  pod 'SVProgressHUD'
  
  target 'PotluckTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
